/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distilleryprototype;

/**
 *
 * @author B
 */
public class InputForm extends javax.swing.JFrame {

    /**
     * Creates new form InputForm
     */
    private MainFrame mainFrame;

public InputForm(MainFrame mainFrame) {
    this.mainFrame = mainFrame;
    initComponents();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Save = new javax.swing.JButton();
        NothingRightNow = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PermeateDensity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FermFeedDensity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FermentationVolume = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FermentationHeelVolume = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FermentorRadius = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Final_abw = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FirstConversion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        HeatCapacityOfWater = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        HeatCapacityOfPermeate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TotalSolids = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        KgShipped = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        NumOfFermentors = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TankerTemp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        HotWaterTemp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        InitialWaterAdded = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        DesiredFermSolids = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 105));
        setPreferredSize(new java.awt.Dimension(550, 500));

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(60, 50));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        Save.setText("Save");
        Save.setPreferredSize(new java.awt.Dimension(100, 25));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save);

        NothingRightNow.setText("just for looks");
        NothingRightNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NothingRightNow.setPreferredSize(new java.awt.Dimension(40, 40));
        NothingRightNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NothingRightNowActionPerformed(evt);
            }
        });
        jPanel1.add(NothingRightNow);

        Cancel.setText("Cancel");
        Cancel.setPreferredSize(new java.awt.Dimension(100, 25));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(466, 466));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 72));
        jPanel4.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 22));

        jLabel3.setText("Permeate density (kg/L)");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel3);

        PermeateDensity.setPreferredSize(new java.awt.Dimension(75, 23));
        PermeateDensity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermeateDensityActionPerformed(evt);
            }
        });
        jPanel4.add(PermeateDensity);

        jLabel4.setText("Ferm feed density(kg/L)");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel4);

        FermFeedDensity.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel4.add(FermFeedDensity);

        jLabel6.setText("Fermentation Volume (L)");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel6);

        FermentationVolume.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel4.add(FermentationVolume);

        jLabel7.setText("Fermentation heel volume (L)");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel7);

        FermentationHeelVolume.setPreferredSize(new java.awt.Dimension(75, 23));
        FermentationHeelVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermentationHeelVolumeActionPerformed(evt);
            }
        });
        jPanel4.add(FermentationHeelVolume);

        jLabel8.setText("Fermenter radius (m)");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel8);

        FermentorRadius.setToolTipText("");
        FermentorRadius.setPreferredSize(new java.awt.Dimension(75, 23));
        FermentorRadius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermentorRadiusActionPerformed(evt);
            }
        });
        jPanel4.add(FermentorRadius);

        jLabel9.setText("Final abw (g/L)");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel9);

        Final_abw.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel4.add(Final_abw);

        jLabel5.setText("First Conversion");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel5);

        FirstConversion.setPreferredSize(new java.awt.Dimension(75, 23));
        FirstConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstConversionActionPerformed(evt);
            }
        });
        jPanel4.add(FirstConversion);

        jLabel18.setText("Heat Capacity of water (kJ/kg°C)");
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel18);

        HeatCapacityOfWater.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel4.add(HeatCapacityOfWater);

        jLabel19.setText("Heat capacity of permeate (kJ/kg°C)");
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel19);

        HeatCapacityOfPermeate.setToolTipText("");
        HeatCapacityOfPermeate.setPreferredSize(new java.awt.Dimension(75, 23));
        HeatCapacityOfPermeate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeatCapacityOfPermeateActionPerformed(evt);
            }
        });
        jPanel4.add(HeatCapacityOfPermeate);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 72));
        jPanel5.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                         INPUTS ");
        jLabel10.setMaximumSize(new java.awt.Dimension(70, 16));
        jLabel10.setMinimumSize(new java.awt.Dimension(70, 16));
        jLabel10.setPreferredSize(new java.awt.Dimension(220, 16));
        jPanel5.add(jLabel10);

        jLabel11.setText("Total Solids (%):");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel11);

        TotalSolids.setMinimumSize(new java.awt.Dimension(64, 25));
        TotalSolids.setPreferredSize(new java.awt.Dimension(75, 23));
        TotalSolids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalSolidsActionPerformed(evt);
            }
        });
        jPanel5.add(TotalSolids);

        jLabel12.setText("kg Shipped");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel12);

        KgShipped.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel5.add(KgShipped);

        jLabel13.setText("No. of Fermentors:");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel13);

        NumOfFermentors.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel5.add(NumOfFermentors);

        jLabel14.setText("Tanker Temperature");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel14);

        TankerTemp.setPreferredSize(new java.awt.Dimension(75, 23));
        TankerTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TankerTempActionPerformed(evt);
            }
        });
        jPanel5.add(TankerTemp);

        jLabel15.setText("Hot Water Temp");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel15);

        HotWaterTemp.setToolTipText("");
        HotWaterTemp.setPreferredSize(new java.awt.Dimension(75, 23));
        HotWaterTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotWaterTempActionPerformed(evt);
            }
        });
        jPanel5.add(HotWaterTemp);

        jLabel16.setText("Initial Water Added psig");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel16);

        InitialWaterAdded.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel5.add(InitialWaterAdded);

        jLabel17.setText("Desired ferm solids");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel17);

        DesiredFermSolids.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel5.add(DesiredFermSolids);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        try {
        // Retrieve values from the input fields
        double totalSolids = Double.parseDouble(TotalSolids.getText());
        double kgShipped = Double.parseDouble(KgShipped.getText());
        int numOfFermentors = Integer.parseInt(NumOfFermentors.getText());
        double tankerTemp = Double.parseDouble(TankerTemp.getText());
        double hotWaterTemp = Double.parseDouble(HotWaterTemp.getText());
        double initialWaterAdded = Double.parseDouble(InitialWaterAdded.getText());
        double desiredFermSolids = Double.parseDouble(DesiredFermSolids.getText());
        double permeateDensity = Double.parseDouble(PermeateDensity.getText());
        double fermFeedDensity = Double.parseDouble(FermFeedDensity.getText());
        double fermentationVolume = Double.parseDouble(FermentationVolume.getText());
        double fermentationHeelVolume = Double.parseDouble(FermentationHeelVolume.getText());
        double fermentorRadius = Double.parseDouble(FermentorRadius.getText());
        double finalAbw = Double.parseDouble(Final_abw.getText());
        double firstConversion = Double.parseDouble(FirstConversion.getText());
        double heatCapacityOfWater = Double.parseDouble(HeatCapacityOfWater.getText());
        double heatCapacityOfPermeate = Double.parseDouble(HeatCapacityOfPermeate.getText());

        // Call the setInputs() method on MainFrame
        mainFrame.setInputs(
            totalSolids, kgShipped, numOfFermentors, tankerTemp, hotWaterTemp,
            initialWaterAdded, desiredFermSolids, permeateDensity, fermFeedDensity,
            fermentationVolume, fermentationHeelVolume, fermentorRadius, finalAbw,
            firstConversion, heatCapacityOfWater, heatCapacityOfPermeate
        );

        // Close the InputForm
        this.dispose();
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers in all fields!");
    }
    }//GEN-LAST:event_SaveActionPerformed

    private void NothingRightNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NothingRightNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NothingRightNowActionPerformed

    private void HotWaterTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotWaterTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HotWaterTempActionPerformed

    private void TankerTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TankerTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TankerTempActionPerformed

    private void TotalSolidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalSolidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalSolidsActionPerformed

    private void HeatCapacityOfPermeateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeatCapacityOfPermeateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeatCapacityOfPermeateActionPerformed

    private void FermentorRadiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermentorRadiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FermentorRadiusActionPerformed

    private void FermentationHeelVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermentationHeelVolumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FermentationHeelVolumeActionPerformed

    private void PermeateDensityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermeateDensityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermeateDensityActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void FirstConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstConversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstConversionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);

            InputForm inputForm = new InputForm(mainFrame);
            inputForm.setVisible(true);
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField DesiredFermSolids;
    private javax.swing.JTextField FermFeedDensity;
    private javax.swing.JTextField FermentationHeelVolume;
    private javax.swing.JTextField FermentationVolume;
    private javax.swing.JTextField FermentorRadius;
    private javax.swing.JTextField Final_abw;
    private javax.swing.JTextField FirstConversion;
    private javax.swing.JTextField HeatCapacityOfPermeate;
    private javax.swing.JTextField HeatCapacityOfWater;
    private javax.swing.JTextField HotWaterTemp;
    private javax.swing.JTextField InitialWaterAdded;
    private javax.swing.JTextField KgShipped;
    private javax.swing.JButton NothingRightNow;
    private javax.swing.JTextField NumOfFermentors;
    private javax.swing.JTextField PermeateDensity;
    private javax.swing.JButton Save;
    private javax.swing.JTextField TankerTemp;
    private javax.swing.JTextField TotalSolids;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
