/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package distilleryprototype;

/**
 *
 * @author B
 */
public class MainFrame extends javax.swing.JFrame {
    private double totalSolids, kgShipped, tankerTemp, hotWaterTemp, initialWaterAdded, desiredFermSolids;
    private double permeateDensity, fermFeedDensity, fermentationVolume, fermentationHeelVolume, fermentorRadius, finalAbw;
    private double firstConversion, heatCapacityOfWater, heatCapacityOfPermeate;
    private int numOfFermentors;
    
    private TankerGraphic tankerGraphic;
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        
        
    tankerGraphic = new TankerGraphic(0, 0, 0, 9000);
    TankerPanel.revalidate();
    TankerPanel.repaint();
    }
    
    private void updateTankerGraphic(double permeateVolume, double waterVolume, double totalVolume, double tankCapacity) {
        tankerGraphic = new TankerGraphic(permeateVolume, waterVolume, totalVolume, tankCapacity);
        TankerPanel.removeAll();
        TankerPanel.revalidate();
        TankerPanel.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        Default_Value = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Save_Inputs = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TopButtons = new javax.swing.JPanel();
        Open_Input = new javax.swing.JButton();
        Default_Value2 = new javax.swing.JButton();
        Default_Value3 = new javax.swing.JButton();
        TankerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));

        ButtonPanel.setBackground(new java.awt.Color(204, 153, 0));
        ButtonPanel.setPreferredSize(new java.awt.Dimension(60, 50));
        ButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        Default_Value.setText("Default value");
        Default_Value.setPreferredSize(new java.awt.Dimension(100, 25));
        ButtonPanel.add(Default_Value);

        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setPreferredSize(new java.awt.Dimension(40, 40));
        ButtonPanel.add(Home);

        Save_Inputs.setText("Save inputs");
        Save_Inputs.setPreferredSize(new java.awt.Dimension(100, 25));
        ButtonPanel.add(Save_Inputs);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        TopButtons.setBackground(new java.awt.Color(0, 0, 0));
        TopButtons.setMinimumSize(new java.awt.Dimension(120, 50));
        TopButtons.setPreferredSize(new java.awt.Dimension(120, 50));
        TopButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 13));

        Open_Input.setText("Open Input");
        Open_Input.setPreferredSize(new java.awt.Dimension(100, 25));
        Open_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_InputActionPerformed(evt);
            }
        });
        TopButtons.add(Open_Input);

        Default_Value2.setText("Calculate");
        Default_Value2.setPreferredSize(new java.awt.Dimension(100, 25));
        Default_Value2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Default_Value2ActionPerformed(evt);
            }
        });
        TopButtons.add(Default_Value2);

        Default_Value3.setText("Save Results");
        Default_Value3.setPreferredSize(new java.awt.Dimension(100, 25));
        TopButtons.add(Default_Value3);

        getContentPane().add(TopButtons, java.awt.BorderLayout.PAGE_START);

        TankerPanel.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout TankerPanelLayout = new javax.swing.GroupLayout(TankerPanel);
        TankerPanel.setLayout(TankerPanelLayout);
        TankerPanelLayout.setHorizontalGroup(
            TankerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        TankerPanelLayout.setVerticalGroup(
            TankerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        getContentPane().add(TankerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Open_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_InputActionPerformed
        InputForm inputForm = new InputForm(this);
        inputForm.setVisible(true);
    }//GEN-LAST:event_Open_InputActionPerformed

    private void Default_Value2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Default_Value2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Default_Value2ActionPerformed
    
    public void setInputs(
    double totalSolids, double kgShipped, int numOfFermentors, double tankerTemp,
    double hotWaterTemp, double initialWaterAdded, double desiredFermSolids,
    double permeateDensity, double fermFeedDensity, double fermentationVolume,
    double fermentationHeelVolume, double fermentorRadius, double finalAbw,
    double firstConversion, double heatCapacityOfWater, double heatCapacityOfPermeate
) {
    this.totalSolids = totalSolids;
    this.kgShipped = kgShipped;
    this.numOfFermentors = numOfFermentors;
    this.tankerTemp = tankerTemp;
    this.hotWaterTemp = hotWaterTemp;
    this.initialWaterAdded = initialWaterAdded;
    this.desiredFermSolids = desiredFermSolids;
    this.permeateDensity = permeateDensity;
    this.fermFeedDensity = fermFeedDensity;
    this.fermentationVolume = fermentationVolume;
    this.fermentationHeelVolume = fermentationHeelVolume;
    this.fermentorRadius = fermentorRadius;
    this.finalAbw = finalAbw;
    this.firstConversion = firstConversion;
    this.heatCapacityOfWater = heatCapacityOfWater;
    this.heatCapacityOfPermeate = heatCapacityOfPermeate;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton Default_Value;
    private javax.swing.JButton Default_Value2;
    private javax.swing.JButton Default_Value3;
    private javax.swing.JButton Home;
    private javax.swing.JButton Open_Input;
    private javax.swing.JButton Save_Inputs;
    private javax.swing.JPanel TankerPanel;
    private javax.swing.JPanel TopButtons;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
    
}
